### ISSUE TITLE
Babel Stage 2 features (e.g. Object Rest/Spread)

### ISSUE THREAD

**Issue by rtsao** [uber/standard#35]
Babel enables [Stage 2+ "experimental" features](https://babeljs.io/docs/usage/experimental/#stage-2) by default, which includes [object rest/spread](https://github.com/sebmarkbage/ecmascript-rest-spread).

This can be enabled in ESLint with `experimentalObjectRestSpread`. Should we enable support for this in uber-standard? I feel that either way, our Babel and ESLint configurations should have parity and support the same things.

Thoughts?

The other experimental features currently enabled by default in Babel are:
- [async/await](https://github.com/lukehoban/ecmascript-asyncawait)
- [exponentiation operator](https://github.com/rwaldron/exponentiation-operator)

My personal opinion is we should support these features so people can use uber/standard instead of rolling their own linting solution or not linting at all.

**Comment by chrisirhc** [comment]
I vote yes. This the rest/spread syntax is helpful in keeping operations that maintain immutability in collections very readable. 

For example, instead of using `Object.assign({}, a, { x: 1, y: 2 });`, I can now do: `{ ...a, x: 1, y: 2 };`. Finally, no xtend/assign needed, and it reads very well.

More examples at (as you linked):
https://github.com/sebmarkbage/ecmascript-rest-spread/blob/master/Spread.md

Some good examples where it could be used are reducers in redux:
http://rackt.github.io/redux/docs/basics/Reducers.html

**Comment by rtsao** [comment]
What about a `--babel` flag which is identical to `--es6` except for the following additional `ecmaFeatures`:
- All default babel transformations
  - JSX `"jsx": true`
  - ES7 Object Rest/Spread `"experimentalObjectRestSpread": true`

A further possibility is using the [babel-eslint](https://github.com/babel/babel-eslint) parser instead of espree when `--babel` is set for more complete Babel support.

I think it makes sense to keep `--es6` limited to strictly ES6 features and maintain a separate `--babel` option for Babel's default experimental features and JSX.

@malandrew @Raynos
